######################################
### Activity Index
GET http://localhost:3000/activities.json

### Activity Show
GET http://localhost:3000/activities/4.json

### Activity Create
POST http://localhost:3000/activities.json
Content-Type: application/json

{
  "name": "hike with dog",
  "user_id": "5"
}

### Activity Update
PATCH http://localhost:3000/activities/15.json
Content-Type: application/json

{
  "name": "cry myself to sleep"
}

### Activity Destroy
DELETE http://localhost:3000/activities/15.json

######################################
### Did_It Index
GET http://localhost:3000/did_its.json

### Did_It Create
POST http://localhost:3000/did_its.json
Content-Type: application/json

{
  "user_id": "1",
  "activity_id": "8",
  "date": "2022-10-11"
}

### Did_It Destroy
DELETE http://localhost:3000/did_its/16.json

######################################
### User Create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "BB",
  "email": "brad.bb.bell@gmail.com"
}

### User Update
PATCH http://localhost:3000/users/5.json
Content-Type: application/json

{
  "name": "BallinBB"
}

### User destroy
DELETE http://localhost:3000/users/5.json